name: CI & CD
on:
    push:
        branches:
            - master
jobs:
    Trigger-Workflows:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger and wait for hexo branch workflow
              env:
                  GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
              run: |
                  gh workflow run main.yml \
                    --repo FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io \
                    --ref hexo

                  echo "Waiting for hexo workflow to start..."
                  sleep 10

                  # Get the latest workflow run ID for hexo branch
                  RUN_ID=$(gh run list \
                    --repo FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io \
                    --workflow main.yml \
                    --branch hexo \
                    --limit 1 \
                    --json databaseId \
                    --jq '.[0].databaseId')

                  echo "Monitoring workflow run ID: $RUN_ID"

                  # Wait for the workflow to complete and fail if it fails
                  gh run watch $RUN_ID \
                    --repo FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io \
                    --exit-status

            - name: Trigger and wait for main branch workflow
              env:
                  GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
              run: |
                  gh workflow run main.yml \
                    --repo FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io \
                    --ref main

                  echo "Waiting for main workflow to start..."
                  sleep 10

                  # Get the latest workflow run ID for main branch
                  RUN_ID=$(gh run list \
                    --repo FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io \
                    --workflow main.yml \
                    --branch main \
                    --limit 1 \
                    --json databaseId \
                    --jq '.[0].databaseId')

                  echo "Monitoring workflow run ID: $RUN_ID"

                  # Wait for the workflow to complete and fail if it fails
                  gh run watch $RUN_ID \
                    --repo FreeCodeCamp-Chengdu/FreeCodeCamp-Chengdu.github.io \
                    --exit-status
